In [1]:
import sys
sys.path.append('../src')

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
from load import load_train_data

pd.set_option('display.max_columns', None)

**GOAL**: predict the level of damage a building 'building_id' suffered as a result of the 2015 earthquake  
- 1 represents low damage
- 2 represents a medium amount of damage
- 3 represents almost complete destruction

In [2]:
# Load data
train_data = load_train_data(local=True)
train_data.shape

(260601, 39)

In [3]:
# Experiment with BaseN encoder
categorical_values = train_data.select_dtypes(include='object')
columns_categorical = categorical_values.columns

from category_encoders import BaseNEncoder

basen_enc = BaseNEncoder(drop_invariant=True, base=1)

X_cat = categorical_values.copy()

basen_enc.fit_transform(X_cat)

,land_surface_condition_1,land_surface_condition_2,land_surface_condition_3,foundation_type_1,foundation_type_2,foundation_type_3,foundation_type_4,foundation_type_5,roof_type_1,roof_type_2,roof_type_3,ground_floor_type_1,ground_floor_type_2,ground_floor_type_3,ground_floor_type_4,ground_floor_type_5,other_floor_type_1,other_floor_type_2,other_floor_type_3,other_floor_type_4,position_1,position_2,position_3,position_4,plan_configuration_1,plan_configuration_2,plan_configuration_3,plan_configuration_4,plan_configuration_5,plan_configuration_6,plan_configuration_7,plan_configuration_8,plan_configuration_10,legal_ownership_status_1,legal_ownership_status_2,legal_ownership_status_3,legal_ownership_status_4
building_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
802906,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
28830,0,1,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
94947,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
590882,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
201944,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
688636,0,0,1,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0
669485,1,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
602512,1,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
151409,1,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0
747594,0,0,1,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0

In [ ]:
from sklearn.preprocessing import TargetEncoder

target_encoder = TargetEncoder(target_type='multiclass')

col_to_encode = ['geo_level_1_id']

X_enc = train_data[col_to_encode].copy()
y_enc = train_data['damage_grade'].copy()

target_encoder.fit(X_enc, y_enc)
target_encoder.transform(X_enc)